### ISSUE TITLE
printing material

### ISSUE THREAD

**Issue by ChangQing-SH** [nerf-common/chronic-neuropixels2#1]
Hi,

Do you have any instruction on the printing materials and assemble?

**Comment by cagjony** [comment]
Sure, you can use our [nature protocol paper ](https://www.nature.com/articles/s41596-021-00539-9), which demonstrates the suitable printing material. If you send me your email, I can send you the detailed assembly protocol for np2, which is more or less the same as described in the protocol paper, but visuals might help.

**Comment by ChangQing-SH** [comment]
thanks, my email: uestcwcq@gmail.com

**Comment by youyikang** [comment]
您好有组装相关的图纸么

**Comment by youyikang** [comment]
> 当然，您可以使用我们的 [自然协议纸 ](https://www.nature.com/articles/s41596-021-00539-9)，它演示了合适的打印材料。如果你把你的电子邮件发给我，我可以给你发np2的详细组装协议，它或多或少与协议文件中描述的相同，但视觉效果可能会有所帮助。

可以也发我一份么229161309@qq.com

**Comment by dprotter** [comment]
Hi there, I'm just hopping on this thread as well. I am trying to produce some fixtures for NPXL 2.0 implants as well. We dont have access to SLS printing, as far as I'm aware, but we do have a bambu labs FFF printer with pretty good resolution (seems good enough for this part) and an anycubic MSLA printer. So id be curious to hear your thoughts on what other materials might be acceptable. david.protter@colorado.edu

**Comment by cagjony** [comment]
Hi David, I have sent you the protocol, and SLA also works since we do most of our prototypes with that material
